---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jackett
  annotations:
    nfs.io/storage-path: "data01/jackett"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
