apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: jackett
spec:
  provider: vault
  secretObjects:
  - secretName: jackett
    type: Opaque
    data: 
    - objectName: VPN_USERNAME
      key: VPN_USERNAME
    - objectName:  VPN_PASSWORD 
      key:  VPN_PASSWORD 
    - objectName: LAN_NETWORK
      key: LAN_NETWORK
    - objectName: WEBUI_PASSWORD
      key: WEBUI_PASSWORD
  parameters:
    vaultAddress: 'http://vault.vault:8200'
    vaultKubernetesMountPath: 'k8s-vault-csi'
    roleName: jackett
    objects: |
      - objectName: "VPN_USERNAME"
        secretPath: "apps-kv/data/jackett/vpn"
        secretKey: "VPN_USERNAME"
      - objectName: "VPN_PASSWORD"
        secretPath: "apps-kv/data/jackett/vpn"
        secretKey: "VPN_PASSWORD"
      - objectName: "LAN_NETWORK"
        secretPath: "apps-kv/data/jackett/vpn"
        secretKey: "LAN_NETWORK"
      - objectName: "WEBUI_PASSWORD"
        secretPath: "apps-kv/data/jackett/webui"
        secretKey: "WEBUI_PASSWORD"
